### ISSUE TITLE
Feedback on website

### ISSUE THREAD

**Issue by gaelbergeron** [sstern6/sstern6.github.io#27]
Hey Scott,
Just went over your website. I like the overall look and feel of the page, the colors are fresh and the surfing picture gives a nice touch. I also like how you added a little color line at the bottom of your social icons when hoovering. 

If I may suggest, here is a list of little improvements and fixes that could be done:
- Center the text in your navigation bar, 
- Use high def icons that would blend a little better with the background, a cool link I found: http://goodstuffnononsense.com/
- When clicking on your social icons it opens in the same window, opening in a new one would be easier to navigate, 
- Styling your blog posts using a template,
- Your images are not aligned with your post titles on the blog index page, you can also work on the spacing, 

It may seem like a lot of suggestions but we all start from scratch and we are all supposed to create a proper maintenance schedule! Feel free to ask for more details or anything else.

Cheers!
Gael

**Comment by sstern6** [comment]
Thanks For the input Gael,

I needed some advice of how to reposition and clean up the design of my site.
