### ISSUE TITLE
Feedback on Technical Blog Post

### ISSUE THREAD

**Issue by XanderPSON** [sstern6/sstern6.github.io#30]
Hey Scott,

I read your Arrays vs Hashes post. I really liked how casual the tone of your post was - it made it feel like you were explaining it to your friends over a beer. I think that tone of voice helps when explaining programming concepts because they are inherently a little intimidating and that aloofness helps brings the stress level down.

That said, I also would recommend cleaning up the formatting a bit. Simple things like proper capitalization, spacing, and punctuation will go a long way in helping your readers go through your post. Those small mistakes distract from the content.

**Comment by sstern6** [comment]
Thanks for the input Xander!

I will take your recommendations and implement them for the future.
